### Site metadata

title: lipu-suli_lukin_taso
description: lipu-suli pi-lipu-mute lon sitelen-pona

### Build settings

url: https://joelthomastr.github.io
baseurl: /lipu-suli_lukin_taso

theme: just-the-docs

defaults:
  - scope:
      path: "*.md"
    values:
      layout: page

exclude:
  - LICENSE
  - README.md
  - sample.png

color_scheme: dark

search_enabled: false
